
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luis Enriquez
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_pr = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_elArbol = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jd_crearPelicula = new javax.swing.JDialog();
        cb_genero = new javax.swing.JComboBox<>();
        tf_nombre = new javax.swing.JTextField();
        s_duracion = new javax.swing.JSpinner();
        tf_actores = new javax.swing.JTextField();
        tf_director = new javax.swing.JTextField();
        tf_compania = new javax.swing.JTextField();
        cb_idioma = new javax.swing.JComboBox<>();
        rb_doblaje = new javax.swing.JRadioButton();
        rb_subtitulos = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jd_crearSerie = new javax.swing.JDialog();
        cb_genero1 = new javax.swing.JComboBox<>();
        tf_nombre1 = new javax.swing.JTextField();
        s_duracion1 = new javax.swing.JSpinner();
        tf_actores1 = new javax.swing.JTextField();
        tf_compania1 = new javax.swing.JTextField();
        cb_idioma1 = new javax.swing.JComboBox<>();
        rb_doblaje1 = new javax.swing.JRadioButton();
        rb_subtitulos1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        s_temp = new javax.swing.JSpinner();
        jd_modPeli = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_pelis = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        pop_pelis = new javax.swing.JPopupMenu();
        pop_modPelis = new javax.swing.JMenuItem();
        pop_eliminar = new javax.swing.JMenuItem();
        jd_nuevaPeli = new javax.swing.JDialog();
        cb_genero2 = new javax.swing.JComboBox<>();
        tf_nombre2 = new javax.swing.JTextField();
        s_duracion2 = new javax.swing.JSpinner();
        tf_actores2 = new javax.swing.JTextField();
        tf_director1 = new javax.swing.JTextField();
        tf_compania2 = new javax.swing.JTextField();
        cb_idioma2 = new javax.swing.JComboBox<>();
        rb_doblaje2 = new javax.swing.JRadioButton();
        rb_subtitulos2 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jd_modSerie = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_pelis1 = new javax.swing.JList<>();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        pop_series = new javax.swing.JPopupMenu();
        pop_modPelis1 = new javax.swing.JMenuItem();
        pop_eliminar1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jf_user = new javax.swing.JTextField();
        jf_pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Recarga el arbol!");
        jt_elArbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_elArbol);

        jButton2.setText("Crear Pelicula");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear Serie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Bienvenido a Nesflis!");

        jButton4.setText("Recargar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Guardar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Cerrar Sesion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton12.setText("Ver Peliculas");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Ver Series");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_prLayout = new javax.swing.GroupLayout(jd_pr.getContentPane());
        jd_pr.getContentPane().setLayout(jd_prLayout);
        jd_prLayout.setHorizontalGroup(
            jd_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_prLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jd_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_prLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_prLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jd_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        jd_prLayout.setVerticalGroup(
            jd_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_prLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_prLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(11, 11, 11)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addGap(13, 13, 13))
                    .addGroup(jd_prLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suspenso", "Terror", "Accion", "Romantica", "SciFi", "Animacion", "Fantasia" }));
        cb_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_generoActionPerformed(evt);
            }
        });

        s_duracion.setModel(new javax.swing.SpinnerNumberModel(120, 60, null, 1));

        cb_idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles", "Alemán", "Francés" }));

        rb_doblaje.setText("Doblaje");

        rb_subtitulos.setText("Subtitulos");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Duracion:");

        jLabel5.setText("Genero:");

        jLabel7.setText("Director:");

        jLabel8.setText("Actores:");

        jLabel9.setText("Compania:");

        jLabel10.setText("Idioma original:");

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Agregar pelicula:");

        javax.swing.GroupLayout jd_crearPeliculaLayout = new javax.swing.GroupLayout(jd_crearPelicula.getContentPane());
        jd_crearPelicula.getContentPane().setLayout(jd_crearPeliculaLayout);
        jd_crearPeliculaLayout.setHorizontalGroup(
            jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                .addComponent(rb_doblaje)
                                .addGap(72, 72, 72)
                                .addComponent(rb_subtitulos))
                            .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_compania, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_director, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearPeliculaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))))
                                    .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(33, 33, 33)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_actores, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearPeliculaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(40, 40, 40))
        );
        jd_crearPeliculaLayout.setVerticalGroup(
            jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                        .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_actores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jd_crearPeliculaLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(25, 25, 25)
                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_compania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(jd_crearPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_doblaje)
                    .addComponent(rb_subtitulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(28, 28, 28))
        );

        cb_genero1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sitcom", "Drama", "Novelas", "Suspenso", "YYY" }));

        s_duracion1.setModel(new javax.swing.SpinnerNumberModel(25, 10, null, 1));

        cb_idioma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles", "Alemán", "Francés" }));

        rb_doblaje1.setText("Doblaje");

        rb_subtitulos1.setText("Subtitulos");

        jLabel12.setText("Nombre:");

        jLabel13.setText("Duracion:");

        jLabel14.setText("Genero:");

        jLabel16.setText("Temporadas:");

        jLabel17.setText("Actores:");

        jLabel18.setText("Productora:");

        jLabel19.setText("Idioma original:");

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Agregar serie:");

        javax.swing.GroupLayout jd_crearSerieLayout = new javax.swing.GroupLayout(jd_crearSerie.getContentPane());
        jd_crearSerie.getContentPane().setLayout(jd_crearSerieLayout);
        jd_crearSerieLayout.setHorizontalGroup(
            jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearSerieLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addComponent(rb_doblaje1)
                                .addGap(72, 72, 72)
                                .addComponent(rb_subtitulos1))
                            .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_compania1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(s_temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearSerieLayout.createSequentialGroup()
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel14))
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)))
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_actores1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s_duracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearSerieLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jd_crearSerieLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearSerieLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearSerieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(40, 40, 40))
        );
        jd_crearSerieLayout.setVerticalGroup(
            jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearSerieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(31, 31, 31)
                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearSerieLayout.createSequentialGroup()
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s_duracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(28, 28, 28)
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_genero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_actores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jd_crearSerieLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(25, 25, 25)
                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(s_temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_compania1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(34, 34, 34)
                .addGroup(jd_crearSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_doblaje1)
                    .addComponent(rb_subtitulos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(28, 28, 28))
        );

        jl_pelis.setModel(new DefaultListModel());
        jl_pelis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_pelisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_pelis);

        jButton9.setText("Cargar Lista");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setText("Salir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modPeliLayout = new javax.swing.GroupLayout(jd_modPeli.getContentPane());
        jd_modPeli.getContentPane().setLayout(jd_modPeliLayout);
        jd_modPeliLayout.setHorizontalGroup(
            jd_modPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modPeliLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_modPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modPeliLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(39, 39, 39))
                    .addGroup(jd_modPeliLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jd_modPeliLayout.setVerticalGroup(
            jd_modPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modPeliLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_modPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton11))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pop_modPelis.setText("Modificar");
        pop_modPelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_modPelisActionPerformed(evt);
            }
        });
        pop_pelis.add(pop_modPelis);

        pop_eliminar.setText("Eliminar");
        pop_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_eliminarActionPerformed(evt);
            }
        });
        pop_pelis.add(pop_eliminar);

        cb_genero2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suspenso", "Terror", "Accion", "Romantica", "SciFi", "Animacion", "Fantasia" }));
        cb_genero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_genero2ActionPerformed(evt);
            }
        });

        s_duracion2.setModel(new javax.swing.SpinnerNumberModel(120, 60, null, 1));

        cb_idioma2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles", "Alemán", "Francés" }));

        rb_doblaje2.setText("Doblaje");

        rb_subtitulos2.setText("Subtitulos");

        jLabel21.setText("Nombre:");

        jLabel22.setText("Duracion:");

        jLabel23.setText("Genero:");

        jLabel25.setText("Director:");

        jLabel26.setText("Actores:");

        jLabel27.setText("Compania:");

        jLabel28.setText("Idioma original:");

        jButton10.setText("Modificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Moficiar pelicula:");

        javax.swing.GroupLayout jd_nuevaPeliLayout = new javax.swing.GroupLayout(jd_nuevaPeli.getContentPane());
        jd_nuevaPeli.getContentPane().setLayout(jd_nuevaPeliLayout);
        jd_nuevaPeliLayout.setHorizontalGroup(
            jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                .addComponent(rb_doblaje2)
                                .addGap(72, 72, 72)
                                .addComponent(rb_subtitulos2))
                            .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_idioma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_compania2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_director1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_nuevaPeliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26)
                                        .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel28)
                                                .addComponent(jLabel27))))
                                    .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(33, 33, 33)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_genero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_actores2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s_duracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevaPeliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(40, 40, 40))
        );
        jd_nuevaPeliLayout.setVerticalGroup(
            jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevaPeliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(31, 31, 31)
                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                        .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s_duracion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(28, 28, 28)
                        .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_genero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_actores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(jd_nuevaPeliLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(25, 25, 25)
                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_director1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_compania2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_idioma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(34, 34, 34)
                .addGroup(jd_nuevaPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_doblaje2)
                    .addComponent(rb_subtitulos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(28, 28, 28))
        );

        jl_pelis1.setModel(new DefaultListModel());
        jl_pelis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_pelis1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_pelis1);

        jButton14.setText("Cargar Lista");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Salir");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modSerieLayout = new javax.swing.GroupLayout(jd_modSerie.getContentPane());
        jd_modSerie.getContentPane().setLayout(jd_modSerieLayout);
        jd_modSerieLayout.setHorizontalGroup(
            jd_modSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modSerieLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd_modSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modSerieLayout.createSequentialGroup()
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton15)
                        .addGap(39, 39, 39))
                    .addGroup(jd_modSerieLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jd_modSerieLayout.setVerticalGroup(
            jd_modSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modSerieLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_modSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pop_modPelis1.setText("Modificar");
        pop_modPelis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_modPelis1ActionPerformed(evt);
            }
        });
        pop_series.add(pop_modPelis1);

        pop_eliminar1.setText("Eliminar");
        pop_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_eliminar1ActionPerformed(evt);
            }
        });
        pop_series.add(pop_eliminar1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Nesflis");

        jButton1.setText("LogIn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        aP.cargarArchivo();
        aS.cargarArchivo();
        
        File f = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            f = new File("./usuarios.txt");
            fr = new FileReader(f);
            br = new BufferedReader(fr);
            boolean log = false;
            String l;
            
            while ((l = br.readLine()) != null) {
                String[] al = l.split(";"); 
                                
                if ((jf_user.getText()).equals(al[0]) && (jf_pass.getText()).equals(al[2])) {
                    log = true;
                }
            }
            
            if (log) {
                jd_pr.setModal(true);
                jd_pr.pack();
                jd_pr.setVisible(true);
                jf_user.setText("");
                jf_pass.setText("");
                                               
            }else{
                    JOptionPane.showMessageDialog(this, "Oops! Revisa los datos!");
            }
            br.close();
            fr.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Oops! Hubo un error!");
        }
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_elArbol.getModel();
        
        File f = new File("./Nesflis");
        m.setRoot(new DefaultMutableTreeNode(f.getName()));
        listar_no_orden(f, ( DefaultMutableTreeNode) m.getRoot());
        
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        
        for (Pelicula p : aP.getlistaPeliculas()) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(p.getNombre());

            if (p.getCateg().equals("Suspenso"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(5)).add(n);
            if (p.getCateg().equals("Terror"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(6)).add(n);
            if (p.getCateg().equals("Accion"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(0)).add(n);
            if (p.getCateg().equals("Romantica"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(3)).add(n);
            if (p.getCateg().equals("SciFi"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(4)).add(n);
            if (p.getCateg().equals("Animacion"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(1)).add(n);
            if (p.getCateg().equals("Fantasia"))
            ((DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(2)).add(n);
                       
        }
        for (Serie s : aS.getListaSeries()) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(s.getNombre());

            if (s.getCateg().equals("Sitcom"))
            ((DefaultMutableTreeNode)raiz.getChildAt(1).getChildAt(2)).add(n);
            if (s.getCateg().equals("Drama"))
            ((DefaultMutableTreeNode)raiz.getChildAt(1).getChildAt(0)).add(n);
            if (s.getCateg().equals("Novelas"))
            ((DefaultMutableTreeNode)raiz.getChildAt(1).getChildAt(1)).add(n);
            if (s.getCateg().equals("Suspenso"))
            ((DefaultMutableTreeNode)raiz.getChildAt(1).getChildAt(3)).add(n);
            if (s.getCateg().equals("YYY"))
            ((DefaultMutableTreeNode)raiz.getChildAt(1).getChildAt(4)).add(n);
            
                       
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jd_crearPelicula.setModal(true);
        jd_crearPelicula.pack();
        jd_crearPelicula.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String nombre = tf_nombre.getText();
            int duracion = (int) s_duracion.getValue();
            String categ = (String) cb_genero.getSelectedItem();
            String actores = tf_actores.getText();
            String director = tf_director.getText();
            String compa = tf_compania.getText();
            String idioma = (String) cb_idioma.getSelectedItem();
            boolean dob = rb_doblaje.isSelected();
            boolean sub = rb_subtitulos.isSelected();

            Pelicula p = new Pelicula(nombre,duracion,categ,actores,director,compa,idioma,dob,sub);
            aP.getlistaPeliculas().add(p);
            
            tf_nombre.setText("");
            s_duracion.setValue(120);
            tf_actores.setText("");
            tf_director.setText("");
            tf_compania.setText("");
            rb_doblaje.setSelected(false);
            rb_subtitulos.setSelected(false);
            
            JOptionPane.showMessageDialog(this, "Se agrego con exito! Pero no se han guardado los cambios");
            
            jd_crearPelicula.setVisible(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hubo un error al guardar!\nIntenta luego!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            String nombre = tf_nombre1.getText();
            int duracion = (int) s_duracion1.getValue();
            String categ = (String) cb_genero1.getSelectedItem();
            String actores = tf_actores1.getText();
            int temp = (int) s_temp.getValue();
            String prod = tf_compania1.getText();
            String idioma = (String) cb_idioma1.getSelectedItem();
            boolean dob = rb_doblaje1.isSelected();
            boolean sub = rb_subtitulos1.isSelected();

            Serie s = new Serie(nombre,duracion,categ,actores,temp,prod,idioma,dob,sub);
            aS.getListaSeries().add(s);
            
            tf_nombre1.setText("");
            s_duracion1.setValue(120);
            tf_actores1.setText("");
            
            tf_compania1.setText("");
            rb_doblaje1.setSelected(false);
            rb_subtitulos1.setSelected(false);
            
            JOptionPane.showMessageDialog(this, "Se agrego con exito! Pero no se han guardado los cambios");
            
            jd_crearSerie.setVisible(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hubo un error al guardar!\nIntenta luego!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jd_crearSerie.setModal(true);
        jd_crearSerie.pack();
        jd_crearSerie.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            aP.escribirArchivo();
            aS.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Guardado con exito!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error al guardar!\nIntenta luego!");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cb_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_generoActionPerformed
        
    }//GEN-LAST:event_cb_generoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jd_pr.setVisible(false);
        try {
            aP.escribirArchivo();
            aS.escribirArchivo();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error al guardar!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DefaultListModel m = (DefaultListModel) jl_pelis.getModel();
        for (Pelicula s: aP.getlistaPeliculas()) {
            m.addElement(s);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jd_modPeli.setModal(true);
        jd_modPeli.pack();
        jd_modPeli.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jd_modPeli.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cb_genero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_genero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_genero2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void pop_modPelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_modPelisActionPerformed
        // TODO add your handling code here:
        if (jl_pelis.getSelectedIndex() >= 0) {
            jd_modPeli.setModal(true);
            jd_modPeli.pack();
            jd_modPeli.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona una pelicula primero!");
        }
    }//GEN-LAST:event_pop_modPelisActionPerformed

    private void jl_pelisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_pelisMouseClicked
        if (evt.isMetaDown()) {
            pop_series.show(evt.getComponent(),evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_pelisMouseClicked

    private void jl_pelis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_pelis1MouseClicked
        if (evt.isMetaDown()) {
            pop_series.show(evt.getComponent(),evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jl_pelis1MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        DefaultListModel m = (DefaultListModel) jl_pelis1.getModel();
        for (Serie s: aS.getListaSeries()) {
            m.addElement(s);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jd_modSerie.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void pop_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_eliminarActionPerformed
        int x = jl_pelis.getSelectedIndex();
        aP.getlistaPeliculas().remove(x);
        JOptionPane.showMessageDialog(this, "Eliminado correctamente!");
    }//GEN-LAST:event_pop_eliminarActionPerformed

    private void pop_modPelis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_modPelis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pop_modPelis1ActionPerformed

    private void pop_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_eliminar1ActionPerformed
        int x = jl_pelis.getSelectedIndex();
        aS.getListaSeries().remove(x);
        JOptionPane.showMessageDialog(this, "Eliminado correctamente!");
    }//GEN-LAST:event_pop_eliminar1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jd_modSerie.setModal(true);
        jd_modSerie.pack();
        jd_modSerie.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void listar_no_orden(File p_raiz, DefaultMutableTreeNode nodo) {
        try {
            for (File temp : p_raiz.listFiles()) {
                if (temp.isFile()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getName());
                    nodo.add(n);
                }else{
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getName());
                    nodo.add(n);
                    listar_no_orden(temp, n);
                }                
            }
        }
        catch (Exception e) {
            
        }
    }
    
    adminPeli aP = new adminPeli("./peliculas.txt");
    
    adminSerie aS = new adminSerie("./series.txt");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_genero1;
    private javax.swing.JComboBox<String> cb_genero2;
    private javax.swing.JComboBox<String> cb_idioma;
    private javax.swing.JComboBox<String> cb_idioma1;
    private javax.swing.JComboBox<String> cb_idioma2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_crearPelicula;
    private javax.swing.JDialog jd_crearSerie;
    private javax.swing.JDialog jd_modPeli;
    private javax.swing.JDialog jd_modSerie;
    private javax.swing.JDialog jd_nuevaPeli;
    private javax.swing.JDialog jd_pr;
    private javax.swing.JTextField jf_pass;
    private javax.swing.JTextField jf_user;
    private javax.swing.JList<String> jl_pelis;
    private javax.swing.JList<String> jl_pelis1;
    private javax.swing.JTree jt_elArbol;
    private javax.swing.JMenuItem pop_eliminar;
    private javax.swing.JMenuItem pop_eliminar1;
    private javax.swing.JMenuItem pop_modPelis;
    private javax.swing.JMenuItem pop_modPelis1;
    private javax.swing.JPopupMenu pop_pelis;
    private javax.swing.JPopupMenu pop_series;
    private javax.swing.JRadioButton rb_doblaje;
    private javax.swing.JRadioButton rb_doblaje1;
    private javax.swing.JRadioButton rb_doblaje2;
    private javax.swing.JRadioButton rb_subtitulos;
    private javax.swing.JRadioButton rb_subtitulos1;
    private javax.swing.JRadioButton rb_subtitulos2;
    private javax.swing.JSpinner s_duracion;
    private javax.swing.JSpinner s_duracion1;
    private javax.swing.JSpinner s_duracion2;
    private javax.swing.JSpinner s_temp;
    private javax.swing.JTextField tf_actores;
    private javax.swing.JTextField tf_actores1;
    private javax.swing.JTextField tf_actores2;
    private javax.swing.JTextField tf_compania;
    private javax.swing.JTextField tf_compania1;
    private javax.swing.JTextField tf_compania2;
    private javax.swing.JTextField tf_director;
    private javax.swing.JTextField tf_director1;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre2;
    // End of variables declaration//GEN-END:variables
}
